version: '3.8'
services:
  luanti:
    image: lscr.io/linuxserver/luanti:latest
    container_name: luanti_server
    restart: unless-stopped
    networks:
      - luanti_network
    ports:
      - "30000:30000/udp"
    volumes:
      - ./luanti-data:/config/.minetest:Z
      - ./mods:/config/.minetest/mods:Z
      - ./games:/config/.minetest/games:Z
      - ./worlds:/config/.minetest/worlds:Z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SERVER_NAME=lrn_helio
      - MAX_PLAYERS=20
      - MOTD=Bienvenido, Agencia La Rana adminisra este servidor.
      - ANNOUNCE_SERVER=false

networks:
  luanti_network:
    external: true
    name: lrn_network
