version: "3.8"

services:
  documentserver:
    image: docker.io/onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    env_file: .env
    ports:
      - "8082:80"
    volumes:
      - oo_logs:/var/log/onlyoffice
      - oo_data:/var/www/onlyoffice/Data
      - oo_lib:/var/lib/onlyoffice
      - oo_db:/var/lib/postgresql
      - oo_rabbitmq:/var/lib/rabbitmq
      - oo_redis:/var/lib/redis
    networks:
      - onlyoffice_net

volumes:
  oo_logs:
  oo_data:
  oo_lib:
  oo_db:
  oo_rabbitmq:
  oo_redis:

networks:
  onlyoffice_net:
    external: true
    name: lrn_network
