version: '3.9'

services:
  redis:
    image: docker.io/redis:7
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:with-curl
    restart: unless-stopped
    ports:
      - "7845:8080"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - evolution_instances:/evolution/instances:Z
    networks:
      - evolution_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  evolution_instances:

networks:
  evolution_network:
    external: true
    name: lrn_network
