version: '3.8'

services:
  adminer:
    image: docker.io/adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    networks:
      - adminer_network

networks:
  adminer_network:
    external: true
    name: lrn_network
