version: '3.8'

services:
  db:
    image: docker.io/postgres:17-alpine
    container_name: postgresql_engine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/podman-entrypoint-initdb.d/init-db.sh:Z
    networks:
      - lrn_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: data_postgres_engine

networks:
  lrn_network:
    external: true
