version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: unless-stopped
    networks:
      - lrn_network
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
      --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 128M

volumes:
  redis_data:

networks:
  lrn_network:
    external: true
