version: '3.8'
services:
  cache:
    image: docker.io/redis:7-alpine
    container_name: redis_service
    restart: always
    env_file:
      - .env
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    volumes: 
      - redis_cache:/data
    networks:
      - redis_network
volumes:
  redis_cache:
    driver: local
networks:
  redis_network:
    external: true
    name: lrn_network
