version: "3.8"

volumes:
    qdrant_storage:

services:
  qdrant:
    image: docker.io/qdrant/qdrant:latest
    container_name: qdrant
    tmpfs:
      - /tmp
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - qdrant_net

networks:
  qdrant_net:
    name: lrn_network
    external: true
